import React from "react";
import Head from "next/head";
import Link from "next/link";
import data from "../../data/data.json";
import { SafeGlobalLogo } from "../assets/SafeGlobalLogo";
import { ArrowBackIcon } from "@chakra-ui/icons";
import { Box, Button } from "@chakra-ui/react";
import { Container } from "@chakra-ui/react";
import { GridItem, Heading, Select, SimpleGrid, Text } from "@chakra-ui/react";

type NftDetailProps = {
  tokenId: string;
};

export default function NftDetail({ tokenId }: NftDetailProps) {
  return (
    <>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Box>
        <Container maxW="1280px">
          <Link href="#">
            <ArrowBackIcon />
          </Link>

          <Box>
            <SimpleGrid columns={10} columnGap={14} rowGap={2}>
              <GridItem colSpan={[10, 10, 10, 4]}>
                <Box>
                  <SafeGlobalLogo />
                </Box>
              </GridItem>

              <GridItem colSpan={[10, 10, 10, 6]}>
                <Heading as="h2">{data.find(item => item.tokenId === tokenId)?.name}</Heading>
                <Text>
                  Descriptione cabrone
                  {/* todo: remove */}
                </Text>

                <Box>
                  <Text>Metadata</Text>
                  <SimpleGrid columns={12} columnGap={5} rowGap={2}>
                    <GridItem colSpan={[12, 6, 6, 6]}>
                      <Box>
                        {" "}
                        <span>Documentname.pdf</span>
                      </Box>
                    </GridItem>
                    <GridItem colSpan={[12, 6, 6, 6]}>
                      <Box>
                        {" "}
                        <span>Audit.pdf</span>
                      </Box>
                    </GridItem>
                  </SimpleGrid>
                </Box>

                <Box>
                  <Text>Owner</Text>
                  <SimpleGrid columns={12} columnGap={5} rowGap={2}>
                    <GridItem colSpan={[12]}>
                      <Box>
                        <span>urataps.eth</span>
                      </Box>
                    </GridItem>
                  </SimpleGrid>
                </Box>

                <Box>
                  <Box>
                    <Text>Rent price</Text>
                    <Heading as={"h3"}>$43.5467 / Day</Heading>
                  </Box>
                  <Box>
                    <Box>
                      <span>Duration</span>
                      <Select placeholder="Select option">
                        <option value="option1">10 Days</option>
                        <option value="option2">15 Days</option>
                        <option value="option3">20 Days</option>
                      </Select>
                    </Box>
                    <Box>
                      <Button>Rent Now</Button>
                    </Box>
                  </Box>
                </Box>
              </GridItem>
            </SimpleGrid>
          </Box>
        </Container>
      </Box>
    </>
  );
}
